import { Bounce, ToastContainer } from "react-toastify";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

import { ThemeProvider, useTheme } from "@/components/themeComponent/themeProvider";

export const metadata = {
  title: "Cinewave",
  description: "Generated by Ruka && Quadds",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className='flex'>
        <ThemeProvider>
          <ToastContainer position='top-right' autoClose={3000} hideProgressBar={false} newestOnTop={false} closeOnClick rtl={false} pauseOnFocusLoss draggable pauseOnHover theme='light' />

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
